# Generated by Django 5.2.14 on 2026-05-13 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='질문 번호')),
                ('category', models.CharField(max_length=20, verbose_name='카테고리')),
                ('question_text', models.CharField(max_length=200, verbose_name='질문 내용')),
                ('choices', models.JSONField(default=list, verbose_name='선택지 및 가중치 데이터')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='팀명')),
                ('region', models.CharField(max_length=50, verbose_name='연고지')),
                ('tag_passion', models.IntegerField(default=0)),
                ('tag_fan_culture', models.IntegerField(default=0)),
                ('tag_story', models.IntegerField(default=0)),
                ('tag_emotional', models.IntegerField(default=0)),
                ('tag_dramatic', models.IntegerField(default=0)),
                ('tag_winning', models.IntegerField(default=0)),
                ('tag_stable', models.IntegerField(default=0)),
                ('tag_traditional', models.IntegerField(default=0)),
                ('tag_loyalty', models.IntegerField(default=0)),
                ('tag_trendy', models.IntegerField(default=0)),
                ('tag_popular', models.IntegerField(default=0)),
                ('tag_underdog', models.IntegerField(default=0)),
                ('tag_analytic', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='질문 번호')),
                ('category', models.CharField(max_length=20, verbose_name='카테고리')),
                ('question_text', models.CharField(max_length=200, verbose_name='질문 내용')),
                ('left_choice', models.CharField(max_length=100, verbose_name='왼쪽 선택지(1점)')),
                ('right_choice', models.CharField(max_length=100, verbose_name='오른쪽 선택지(5점)')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=50, verbose_name='선수 한글명')),
                ('number', models.IntegerField(verbose_name='등번호')),
                ('position', models.CharField(max_length=20, verbose_name='포지션')),
                ('tag_power', models.IntegerField(default=0)),
                ('tag_contact', models.IntegerField(default=0)),
                ('tag_speed', models.IntegerField(default=0)),
                ('tag_defense', models.IntegerField(default=0)),
                ('tag_ace', models.IntegerField(default=0)),
                ('tag_closer', models.IntegerField(default=0)),
                ('tag_clutch', models.IntegerField(default=0)),
                ('tag_consistent', models.IntegerField(default=0)),
                ('tag_charisma', models.IntegerField(default=0)),
                ('tag_leader', models.IntegerField(default=0)),
                ('tag_young', models.IntegerField(default=0)),
                ('tag_underdog', models.IntegerField(default=0)),
                ('tag_foreign', models.IntegerField(default=0)),
                ('stats', models.JSONField(default=dict, verbose_name='주요 스탯')),
                ('intro', models.CharField(max_length=100, verbose_name='한줄 소개')),
                ('story', models.TextField(verbose_name='선수 스토리')),
                ('watch_point', models.CharField(max_length=200, verbose_name='관전 포인트')),
                ('cheer', models.TextField(verbose_name='응원가 가사')),
                ('stadium_tip', models.CharField(max_length=200, verbose_name='직관 꿀팁')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='baseball.team')),
            ],
        ),
    ]
