# Generated by Django 5.2.14 on 2026-05-14 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ko', models.CharField(max_length=50, verbose_name='선수 한글명')),
                ('number', models.IntegerField(verbose_name='등번호')),
                ('position', models.CharField(max_length=20, verbose_name='포지션')),
                ('is_active', models.BooleanField(default=True, verbose_name='현역 여부')),
                ('is_recommendable', models.BooleanField(default=True, verbose_name='추천 대상 여부')),
                ('intro', models.CharField(max_length=200, verbose_name='한줄 소개')),
                ('story', models.TextField(verbose_name='선수 스토리')),
                ('watch_point', models.CharField(max_length=300, verbose_name='관전 포인트')),
                ('cheer', models.TextField(verbose_name='응원가 가사')),
                ('stadium_tip', models.CharField(max_length=300, verbose_name='직관 꿀팁')),
            ],
            options={
                'verbose_name': '선수',
                'verbose_name_plural': '선수 목록',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='팀명')),
                ('region', models.CharField(max_length=50, verbose_name='연고지')),
                ('stadium', models.CharField(default='', max_length=100, verbose_name='홈구장')),
                ('intro', models.TextField(default='', verbose_name='팀 소개')),
            ],
            options={
                'verbose_name': '팀',
                'verbose_name_plural': '팀 목록',
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField(default=2025, verbose_name='시즌 연도')),
                ('stats', models.JSONField(default=dict, verbose_name='시즌 기록')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='baseball.player', verbose_name='선수')),
            ],
            options={
                'verbose_name': '선수 시즌 기록',
                'verbose_name_plural': '선수 시즌 기록 목록',
            },
        ),
        migrations.CreateModel(
            name='PlayerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=0, verbose_name='파워')),
                ('contact', models.IntegerField(default=0, verbose_name='컨택')),
                ('speed', models.IntegerField(default=0, verbose_name='스피드')),
                ('defense', models.IntegerField(default=0, verbose_name='수비')),
                ('ace', models.IntegerField(default=0, verbose_name='에이스')),
                ('closer', models.IntegerField(default=0, verbose_name='마무리')),
                ('clutch', models.IntegerField(default=0, verbose_name='클러치')),
                ('consistent', models.IntegerField(default=0, verbose_name='꾸준함')),
                ('charisma', models.IntegerField(default=0, verbose_name='카리스마')),
                ('leader', models.IntegerField(default=0, verbose_name='리더십')),
                ('young', models.IntegerField(default=0, verbose_name='유망주')),
                ('underdog', models.IntegerField(default=0, verbose_name='언더독')),
                ('foreign', models.IntegerField(default=0, verbose_name='외국인')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='baseball.player', verbose_name='선수')),
            ],
            options={
                'verbose_name': '선수 태그',
                'verbose_name_plural': '선수 태그 목록',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('team', '팀 추천'), ('player', '선수 추천')], max_length=10, verbose_name='질문 유형')),
                ('number', models.IntegerField(verbose_name='질문 번호')),
                ('category', models.CharField(max_length=30, verbose_name='카테고리')),
                ('question_text', models.CharField(max_length=300, verbose_name='질문 내용')),
                ('input_type', models.CharField(choices=[('slider', '슬라이더'), ('button', '버튼')], default='button', max_length=10, verbose_name='입력 방식')),
                ('is_conditional', models.BooleanField(default=False, verbose_name='조건부 노출')),
                ('condition_key', models.CharField(blank=True, default='', max_length=50, verbose_name='노출 조건 키')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문 목록',
                'ordering': ['quiz_type', 'number'],
                'unique_together': {('quiz_type', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='선택지 텍스트')),
                ('key', models.CharField(max_length=50, verbose_name='선택 키')),
                ('display_order', models.IntegerField(default=0, verbose_name='노출 순서')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='baseball.question', verbose_name='질문')),
            ],
            options={
                'verbose_name': '선택지',
                'verbose_name_plural': '선택지 목록',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='baseball.team', verbose_name='소속 팀'),
        ),
        migrations.CreateModel(
            name='TeamTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passion', models.IntegerField(default=0, verbose_name='열정')),
                ('fan_culture', models.IntegerField(default=0, verbose_name='응원문화')),
                ('story', models.IntegerField(default=0, verbose_name='서사')),
                ('emotional', models.IntegerField(default=0, verbose_name='감성')),
                ('dramatic', models.IntegerField(default=0, verbose_name='드라마틱')),
                ('winning', models.IntegerField(default=0, verbose_name='승리지향')),
                ('stable', models.IntegerField(default=0, verbose_name='안정')),
                ('traditional', models.IntegerField(default=0, verbose_name='전통')),
                ('loyalty', models.IntegerField(default=0, verbose_name='충성도')),
                ('trendy', models.IntegerField(default=0, verbose_name='트렌디')),
                ('popular', models.IntegerField(default=0, verbose_name='인기')),
                ('underdog', models.IntegerField(default=0, verbose_name='언더독')),
                ('analytic', models.IntegerField(default=0, verbose_name='분석')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='baseball.team', verbose_name='팀')),
            ],
            options={
                'verbose_name': '팀 태그',
                'verbose_name_plural': '팀 태그 목록',
            },
        ),
    ]
